apiVersion: v1
kind: PersistentVolume
metadata:
  name: base-volume
  labels:
    type: local
spec:
  storageClassName: volumen
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"